In [1]:
import numpy as np

In [3]:
# creation of numpy array
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# shape and size
print(x.size)
print(x.shape)

5
(5,)


In [6]:
x2d=np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x2d.size)
print(x2d.shape)

[[1 2 3]
 [4 5 6]]
6
(2, 3)


In [8]:
x25=np.random.randint(1,100,(5,5))
print(x25)

[[31 94 74  3 18]
 [43 33 68 67 89]
 [32 43 74  1 75]
 [56 75 28  2 91]
 [14 26 77 64 88]]


In [13]:
xseq1=np.arange(1,101,4)
print(xseq1)
print(xseq1.size)
print(xseq1.reshape(5,5))

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [16]:
xseq2=np.linspace(1,100,50)
print(xseq2)
print(xseq2.size)
print(xseq2.reshape(10,5))

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
50
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.4897959

In [17]:
print(x25[0])

[31 94 74  3 18]


In [19]:
print(x25[-1])


[14 26 77 64 88]


In [20]:
print(x25[0,1])

94


In [21]:
print(x25[:,1])


[94 33 43 75 26]


In [22]:
print(x25[:,0])
print(x25[:,-1])


[31 43 32 56 14]
[18 89 75 91 88]


In [23]:
np.append(x25,[1,2,3,4,5])

array([31, 94, 74,  3, 18, 43, 33, 68, 67, 89, 32, 43, 74,  1, 75, 56, 75,
       28,  2, 91, 14, 26, 77, 64, 88,  1,  2,  3,  4,  5])

In [28]:
np.append(x25,np.array([[1,2,3,4,5]]), axis=0)


array([[31, 94, 74,  3, 18],
       [43, 33, 68, 67, 89],
       [32, 43, 74,  1, 75],
       [56, 75, 28,  2, 91],
       [14, 26, 77, 64, 88],
       [ 1,  2,  3,  4,  5]])

In [33]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[4,5]])
print(a.shape)
print(b.shape)

(2, 3)
(3, 2)


In [34]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
np.hstack((a.T,b))

array([[1, 4, 1, 2],
       [2, 5, 3, 4],
       [3, 6, 4, 5]])